name: Publish Docker image (DockerHub)

on:
    push:
        branches: ['main']

env:
    NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
    IMAGE_NAME: qiskit-metal

jobs:
    build-and-push-image-dockerhub:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker (ubuntu image)
              id: meta-ubuntu
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  tags: |
                      type=raw,value=latest
                      type=raw,value=latest-ubuntu
                  images: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}

            - name: Build and push Docker ubuntu image
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./ubuntu.Dockerfile
                  push: true
                  tags: ${{ steps.meta-ubuntu.outputs.tags }}
                  labels: ${{ steps.meta-ubuntu.outputs.labels }}

            - name: Extract metadata (tags, labels) for Docker (minimal-jupyter image)
              id: meta-minimal-jupyter
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  tags: type=raw,value=latest-minimal-jupyter
                  images: ${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}

            - name: Build and push Docker minimal-jupyter image
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./minimal-jupyter.Dockerfile
                  push: true
                  tags: ${{ steps.meta-minimal-jupyter.outputs.tags }}
                  labels: ${{ steps.meta-minimal-jupyter.outputs.labels }}
